### ISSUE TITLE
Style the timing information properly

### ISSUE THREAD

**Issue by ayende** [ayende/appliance-demo#13]
![image](https://github.com/ayende/appliance-demo/assets/116915/13b23f01-bb2e-402c-9f10-fe200a05aa5b)

**Comment by kwiato** [comment]
![image](https://github.com/ayende/appliance-demo/assets/11148407/4ed6b06b-0c02-48e2-a4a1-ee1ad08d4b32)

**Comment by ayende** [comment]
Can you set it so the numbers are aligned across items?
