### ISSUE TITLE
Make tags in search page pretty

### ISSUE THREAD

**Issue by ayende** [ayende/appliance-demo#3]
Currently

![image](https://github.com/ayende/appliance-demo/assets/116915/9c55839d-02b7-455f-9d23-807be85afe6e)

**Comment by kwiato** [comment]
![image](https://github.com/ayende/appliance-demo/assets/11148407/bd6b87a4-bbae-42b7-a669-c12533ac7460)

**Comment by ayende** [comment]
Can you set it so the locations of the communities are fixed?

**Comment by ayende** [comment]
![image](https://github.com/ayende/appliance-demo/assets/116915/4ffd3133-0be8-453d-87f2-7db5c8d1e867)
Move this to the right, I mean

**Comment by kwiato** [comment]
how about this? :)
![image](https://github.com/ayende/appliance-demo/assets/11148407/cb5d6221-dd10-46f3-8dd9-438df6776c7e)

**Comment by kwiato** [comment]
Updated serverfault
![image](https://github.com/ayende/appliance-demo/assets/11148407/880f76fd-667f-423a-86ff-e4a1737de4fe)

**Comment by ayende** [comment]
Much nicer!
