### ISSUE TITLE
Make paging pretty (search page)

### ISSUE THREAD

**Issue by ayende** [ayende/appliance-demo#30]
![image](https://github.com/ayende/appliance-demo/assets/116915/eb8fbf4f-4078-4e10-bf32-f4cf9dbba4ae)

They are currently at the very bottom - need to think how to make this more visible

**Comment by kwiato** [comment]
![image](https://github.com/ayende/appliance-demo/assets/11148407/f97e4411-e984-4ab8-977b-5510c93a113e)
