### ISSUE TITLE
Fix the height of the super user icon on main page

### ISSUE THREAD

**Issue by ayende** [ayende/appliance-demo#32]
![image](https://github.com/ayende/appliance-demo/assets/116915/94854657-e173-47e5-ad8d-95d52934add9)

**Comment by kwiato** [comment]
![image](https://github.com/ayende/appliance-demo/assets/11148407/c19ab39a-f9ad-4c7e-9b10-367fcc3b2482)

**Comment by ayende** [comment]
thanks
