### ISSUE TITLE
Bad artifact on search page?

### ISSUE THREAD

**Issue by ayende** [ayende/appliance-demo#33]
http://127.0.0.1:5173/search?q=bash

![image](https://github.com/ayende/appliance-demo/assets/116915/502f9a91-c282-424f-aace-83fa74860c84)

**Comment by ayende** [comment]
May need to scroll down

**Comment by ayende** [comment]
Pretty sure that this is beause of the super user icon

**Comment by kwiato** [comment]
![image](https://github.com/ayende/appliance-demo/assets/11148407/94984036-4a39-4b32-81c7-ba6b6119f891)
