### ISSUE TITLE
Display select tag & community

### ISSUE THREAD

**Issue by ayende** [ayende/appliance-demo#9]
Can be here or next to the search input

![image](https://github.com/ayende/appliance-demo/assets/116915/773a857c-9978-47a7-8b17-c2df8b3dc0c9)

Should be able to _remove_ this as well

**Comment by EshelEyni** [comment]
* above backend timing in search page. 
* need to render list of tags and comunities that were added to the filter.
* have x btn to remove curr filter from params.
* have sort order options beneath it.
